use bsc;
CREATE TABLE student_details (
    SI_NO INT NOT NULL AUTO_INCREMENT,
    student_id VARCHAR(15) NOT NULL UNIQUE,
    STUDENT_NAME VARCHAR(255) NOT NULL,
    hostel_id VARCHAR(15) DEFAULT NULL,
    FATHER_NAME VARCHAR(255) DEFAULT NULL,
    MOTHER_NAME VARCHAR(255) DEFAULT NULL,
    PRIMARY_GUARDIAN VARCHAR(255) DEFAULT NULL,
    PRIMARY_NO VARCHAR(15) DEFAULT NULL,
    SECONDARY_NO VARCHAR(15) DEFAULT NULL,
    student_status INT DEFAULT NULL,
    EMAIL VARCHAR(255) DEFAULT NULL UNIQUE,
    PRIMARY KEY (SI_NO)
);
