use bsc;
CREATE TABLE user_details (
    user_id INT NOT NULL AUTO_INCREMENT UNIQUE,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    PERMISSION INT NOT NULL,
    PRIMARY KEY (USER_NAME)
);
